apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: calculatorapi
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: calculatorapi
    spec:
      containers:
      - name: calculatorapi
        image: yourrepo/calculatorapi:v{yourversion}
        ports:
        - containerPort: 80
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Development"
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: calculatorapi-srv
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30037
  selector:
    app: calculatorapi